pull_request_rules:
  - name: Merge on CI success and review approval
    conditions:
      - -merged
      - -closed
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
    actions:
      merge:
        method: squash
